---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "chatterbox.serviceName" . }}'
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "chatterbox.labels" . | indent 4 }}
spec:
  selector:
{{ include "chatterbox.selectorLabels" . | indent 4 }}
  ports:
    - name: cbox-plain
      protocol: TCP
      port: 80
      targetPort: cbox-plain
