FROM opensuse/leap:15.5
LABEL Name=chatterbox-test

RUN zypper -n install --no-recommends curl \
&& zypper clean --all

RUN mkdir -p /wd/scenarios
COPY scenarios /wd/scenarios

COPY cbx_test /usr/bin/cbx_test

WORKDIR /wd
ENTRYPOINT ["cbx_test"]
