FROM opensuse/leap
LABEL Name=chatterbox

RUN zypper -n install --no-recommends curl \
&& zypper clean --all

RUN mkdir /monitor
VOLUME /monitor

COPY chatterbox /usr/bin/chatterbox

ENTRYPOINT ["chatterbox"]
