FROM opensuse/tumbleweed
LABEL Name=chatterbox-opensuse

RUN zypper -n install --no-recommends \
    sudo dnf bash curl

RUN zypper clean --all

RUN mkdir /monitor
VOLUME /monitor

COPY chatterbox /usr/bin/chatterbox

ENTRYPOINT ["chatterbox"]
